<?php
namespace frontend\controllers;

use common\helpers\SysMsg;
use common\models\User;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

class BaseController extends Controller
{
    const POST_VALID_TOKEN = 'params_validate_token';
    const PAGE_SIZE = 20;

    public function behaviors()
    {
        return [
            'log' => 'common\filters\LogFilter',
        ];
    }

    public function beforeAction($action)
    {
        if (!isset(Yii::$app->user->identity->id) || !Yii::$app->user->identity->id) {
            return $this->toLogin();
        }
        if (!$this->dataValidate()) {
            return $this->validErr();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function toLogin()
    {
        Yii::$app->response->data = SysMsg::getErrData('C_USER_TO_LOGIN');
        Yii::$app->response->send();
    }

    public function validErr()
    {
        Yii::$app->response->data = SysMsg::getErrData('C_VALID_ERR');
        Yii::$app->response->send();
    }

    public function dataValidate()
    {
        $postData = Yii::$app->request->post();
        $dataStr = '';
        $token = ArrayHelper::getValue($postData, self::POST_VALID_TOKEN, '');
        if (!empty($postData) && !$token) {
//            return false;
        }
        foreach ($postData as $key => $value) {
            if ($key == self::POST_VALID_TOKEN) {
                continue;
            }
            $dataStr .= $key .'='. $value .';';
        }
        if (strlen($dataStr) > 0) {
            return $token == md5($dataStr);
        }
        return true;
    }
}
SysMsg::register('C_USER_TO_LOGIN', '请登录', 10);
SysMsg::register('C_VALID_ERR', '数据不完整错误', 1);